
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.main;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 13;
  public static final int ELSE = 10;
  public static final int SETPENDOWN = 3;
  public static final int OR = 14;
  public static final int THEN = 9;
  public static final int SEMI = 16;
  public static final int WHILE = 11;
  public static final int NOT = 15;
  public static final int COLOR = 25;
  public static final int RKEY = 18;
  public static final int ISPENUP = 23;
  public static final int IF = 8;
  public static final int LKEY = 17;
  public static final int DO = 12;
  public static final int ISBOARDCOLOR = 19;
  public static final int SETPENDIR = 6;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int EDGE = 20;
  public static final int ISPENDOWN = 24;
  public static final int CHECKPENDIR = 21;
  public static final int DIRECTION = 26;
  public static final int SETPENUP = 4;
  public static final int error = 1;
  public static final int CHECKPENCOLOR = 22;
  public static final int MOVE = 7;
  public static final int SETPENCOLOR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "SETPENDOWN",
  "SETPENUP",
  "SETPENCOLOR",
  "SETPENDIR",
  "MOVE",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "AND",
  "OR",
  "NOT",
  "SEMI",
  "LKEY",
  "RKEY",
  "ISBOARDCOLOR",
  "EDGE",
  "CHECKPENDIR",
  "CHECKPENCOLOR",
  "ISPENUP",
  "ISPENDOWN",
  "COLOR",
  "DIRECTION"
  };
}

